export const chefNames = [
  'Chicago Homegrown Electronic Funk',
  'Celebrating Homies’ Eternal Friendship',
  'Creating Harmonics Every Friday',
  'Coupla’ Homies Exchanging Frequencies',
  'Crushing Hummus Especially Fast',
  'Calculating Hard Equilateral Formulas',
  'Cursing Heavenly Elves Ferociously',
  'Curating Harmonious Events Frequently',
  'Cousin Harry Enters Fashionably',
  'Cementing Hot Erotic Feelings',
  'Cooking Heavy Electronic Funk',
  'Crunk Habit Even Fly',
  'Can Hold Eleven Flip-Flops',
  'Carrying Heavy Envelopes Far',
  'Creating High Energy Funk',
  'Constructing High Effort Fun',
  'Creating Happy Elevated Feelings',
  'Couches Hardly Even Flop',
  'Creating Happy Electric Fun',
  'Causing Healthy Enjoyable Feelings',
  'Clothing Homeless, Elders, and Families',
  'Chicago Homegrown Established Funkyboys',
  'Corned Ham Every Friday',
  'Crunchy Homemade Exuberant Falafel',
  'Creamsicles Have Every Flavor',
  'Chicago Hotdog Extra Fries',
  'Can’t Have Enough Fun',
  'Chicago Has Extreme Funk',
  'Chicago Is Home Everyone Is Family',
];
